name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Run tests
        run: make test
      - name: Run build
        run: make build
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: tflint-ruleset-module-verification-${{ matrix.os }}
          path: tflint-ruleset-module-verification
